
#  spring.datasource.url=jdbc:mysql://localhost:3307/aiacademy?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#  spring.datasource.username=root
spring.datasource.url=jdbc:mysql://mysql-1bf3b1d2-ishashaik1509-3de1.k.aivencloud.com:22479/defaultdb?ssl-mode=REQUIRED&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_2C2hDhbIRq0Dw2HrCB9

 spring.jpa.hibernate.ddl-auto=update
 spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=IshaProjectSecretKey2025!@#AI_ACADEMY_786
jwt.expirationMs=86400000
# # ✅ Multipart enable
spring.servlet.multipart.enabled=true

# # ✅ File size limits
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# # ✅ Tomcat timeout (important)
server.tomcat.connection-timeout=300000

file.upload.video-dir=uploads/video
file.upload.thumb-dir=uploads/thumb
